### PR TITLE
added option for rabbitmq vhost

### PR DESCRIPTION
**Pull request by dagbru**
Adding optional parameter for rabbitmq to specify VirtualHost

### CODE REVIEW

**Comment by jarleborsheim** [comment]
Cool! We'll take a look and come back to you soon 👍

**Comment by dagbru** [comment]
Have you had a chance to look into this? :)

**Review by jarleborsheim — APPROVED** [review]
LGTM 👍

**Comment by jarleborsheim** [comment]
Yes. We have discussed this and it is approved. We'll release a new version very soon

**Pull request merged**
